spring:
  datasource:
    url: jdbc:mysql://containers-us-west-123.railway.app:6716/railway
    username: root
    password: ApYLfvgX5d6rtZLCLUdn
  jpa :
    database-platform : org.springframework.orm.jpa.vendor.Database.MYSQL
    generate-ddl : true
    show-sql : true
    hibernate :
      ddl-auto : update
    properties :
      hibernate :
        globally_quoted_identifiers : true
        dialect : org.hibernate.dialect.MySQLDialect
        format_sql : true

  # Mail settings
  mail:
    host: smtp.gmail.com
    port: 587
    username: aaronprojectemail@gmail.com
    password: ddqpzofveafaxltr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true